config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :categories  do
    resources :payments, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "users#welcome"




end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_and_belongs_to_many :categories

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :acq_category
  before_action :acq_categories
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @payments = @category.payments
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = current_user.payments.build
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = current_user.payments.build(payment_params)
    respond_to do |format|
      if @payment.save
        @payment.categories << acq_categories
        format.html { redirect_to category_payments_path(@category), notice: 'payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to category_payments_path, notice: 'payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  def acq_category
    @category = Category.find(params[:category_id])
  end

  def acq_categories
    categories = []
    selected_category = Category.find(params[:category_id])
    extra_categories = params[:categories] ? Category.where(id: params[:categories][:category_ids]).to_a : []
    categories << selected_category << extra_categories
    categories.flatten
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, :user_id)
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, url: category_payments_path(@category)) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class= "form-payment">
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>


  

  <div>
  <%= fields_for :categories do |extra_categories| %>
  <%= extra_categories.collection_check_boxes( :category_ids, Category.where(user: current_user), :id, :name, include_hidden: false) do |b| %>
  <% if b.value != params[:category_id].to_i %>
    <li>
      <%= b.check_box %>
      <%= b.label %>
    </li>
  <% end %>
  <% end %>
  <%end%>
  </div>
</div>
  <div class="btn-form-div">
    <%= form.submit "Create new Payment", :class => 'btn-form' %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>amount:</strong>
    $<%= payment.amount %>
  </p>

  <p>
    <strong>User:</strong>
    <%= payment.user_id %>
  </p>



</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<%= render "shared/navbar" %>
<p style="color: green"><%= notice %></p>

<h1 class="payment-font">Payments</h1>
<div class= "cat-name">
<%= @category.name %>
</div>
<div id="payments">
  <% @payments.each do |payment| %>
  
    <%= render payment %>
    <p class="show-pay">
     <%= link_to "Show this payment", category_payment_path(@category, payment) %>

    </p>
  <% end %>
<div class= "links-shared">
<div>
<%= link_to "New payment", new_category_payment_path(@category) %>

<%= link_to "Back to categories", categories_path %>
</div>

app/views/payments/new.html.erb
<%= render "shared/navbar" %>
<h1 class="payment-font">New payment</h1>

<%= render "form", payment: @payment %>

<br>

<div class ="links-shared">
  <%= link_to "Back to payments", category_payments_path %>
</div>

app/views/payments/show.html.erb
<%= render "shared/navbar" %>
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Back to payments", category_payments_path %>

  <%= button_to "Destroy this Payment", @payment_path, method: :delete %>
</div>