config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :categories  do
    resources :payments, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "users#welcome"




end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :payments

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount_category
    total = 0
    payments.each do |payment|
      total += payment.amount
    end
    total.round(2)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories.includes([:categories_payments]).includes([:payments])
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  
  <div id="dom_id">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

 

<img class="newcategory_img" src="<%=asset_path("#{category.icon}.png") %>">

<p>
      $ <%= category.total_amount_category %>
    </p>

</div>

app/views/categories/_form.html.erb
<% icon_categories =[
    {
      icon: 'airplane',
      title: 'airplane',
    },
    {
      icon: 'art',
      title: 'art',
    },
    {
      icon: 'car',
      title: 'car',
    },
    {
      icon: 'entertainment',
      title: 'entertainment',
    },
    {
      icon: 'fashion',
      title: 'fashion',
    },
    {
      icon: 'food',
      title: 'food',
    },
    {
      icon: 'furniture',
      title: 'furniture',
    },
    {
      icon: 'health',
      title: 'health',
    },
    {
      icon: 'home',
      title: 'home',
    },
    {
      icon: 'insurance',
      title: 'insurance',
    },
    {
      icon: 'medicine',
      title: 'medicine',
    },
    {
      icon: 'movie',
      title: 'movie',
    },
    {
      icon: 'music',
      title: 'music',
    },
    {
      icon: 'pet',
      title: 'pet',
    },
    {
      icon: 'restaurant',
      title: 'restaurant',
    },
    {
      icon: 'shoe',
      title: 'shoe',
    },
    {
      icon: 'sport',
      title: 'sport',
    },
    {
      icon: 'studying',
      title: 'studying',
    },
    {
      icon: 'tech',
      title: 'tech',
    },
    {
      icon: 'transportation',
      title: 'transportation',
    },
] %>

<div class="newcategory_container">
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="newcategory_field">
    <%= form.label :name, style: "display: block", class: 'form_label' %>
    <%= form.text_field :name, class: 'form_input' %>
  </div>
   <p class="newcategory_text">Select an icon from the list</p>
  
    <ul class="newcategory_option">
    
    <% icon_categories.each do |icon_category|%>
      <li class="newcategory_option-list">
        <%= form.radio_button :icon, icon_category[:icon] %> 
        <img class="newcategory_img" src="<%=asset_path("#{icon_category[:icon]}.png") %>" alt=<%=icon_category[:title]%>>
      </li>
       <% end %>
    </ul>
  <div class="newcategory_button">
    <%= form.submit :class => 'btn-form'%>
  </div>
<% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= render "shared/navbar"  %>
<p style="color: green"><%= notice %></p>
<div class="categories">
<h2 class="categories_title">Categories:</h2>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p id="newcategory_button">
      <%= link_to "Show this category", category, class: "btn-form" %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path, class: "btn-category" %>

app/views/categories/new.html.erb
<%= render "shared/navbar" %>


<div class="newcategory">
<h2 class="newcategory_title">New category</h2>

<%= render "form", category: @category %>

</div>

app/views/categories/show.html.erb
<%= render "shared/navbar" %>
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div class="show-btn">
  <%= link_to "Edit this category", edit_category_path(@category) %> 
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete, class: "destroy-btn" %>
  <%= link_to category_payments_path(@category) do %>See Payments<% end %>

</div>